# wallust template - colors-hyprland

$background = rgb(181B1E)
$backgroundAlpha = rgba(181B1EB3)
$foreground = rgb(FAEBC4)
$color0 = rgb(42464A)
$color1 = rgb(606A77)
$color2 = rgb(636A70)
$color3 = rgb(7A7173)
$color4 = rgb(7A869A)
$color5 = rgb(778A8F)
$color6 = rgb(B49540)
$color7 = rgb(EFDBA2)
$color8 = rgb(A79971)
$color9 = rgb(6C7B8C)
$color10 = rgb(707B82)
$color11 = rgb(8F8386)
$color12 = rgb(99ABC6)
$color13 = rgb(9FB9BE)
$color14 = rgb(F0C756)
$color15 = rgb(EFDBA2)
