# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



# wallust generated colors
source = /home/nyx/.config/hypr/wallust/colors-hyprland.conf

# monitors
source = /home/nyx/.config/hypr/monitors.conf
source = /home/nyx/.config/hypr/workspaces.conf


$mainMod = SUPER
$terminal = ghostty
$fileManager = thunar
$menu = rofi -show drun

# Load hyprpm plugins (hy3 layout, hyprEasymotion) on startup
exec-once = hyprpm reload -n

# Autostart
exec-once = waybar
exec-once = swaync
exec-once = hypridle
exec-once = sunsetr
exec-once = swayosd-server
exec-once = awww-daemon & sleep 1 && awww img "/home/nyx/Photos/Wallpapers/Oslo Opera House.jpg"

# Tiling layout, gaps, borders, groups
source = /home/nyx/.config/hypr/looknfeel.conf

# i3/sway-style keybindings
source = /home/nyx/.config/hypr/keybinds.conf
