-- Generated by nwg-displays on 2026-06-02 at 13:50:40. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "3840x1042",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@60.0",
    position = "0x1042",
    scale = 0.9999999999999997
})
